### PR TITLE
Add Travis CI

### PR DESCRIPTION
**Pull request by VictorLamoine**

### CODE REVIEW

**Comment by 130s** [comment]
Jumping from [ML thread](https://groups.google.com/d/msg/swri-ros-pkg-dev/xP8GJ0Dx_6M/sjhsmTq5BAAJ),

you can define "pre-CI" script. In my [recent PR](https://github.com/ros-industrial/industrial_ci/pull/15) where I documented this, for instance, you can define extra installation steps [in pre-process.sh](https://github.com/ros-industrial/industrial_ci/pull/15/files#diff-354f30a63fb0907d4ad57269548329e3R37) (or whatever you name the script).

By the way, although this has nothing to do with the error you're seeing, `git clone` method is recommended now instead of `git submodule`, to enable to use the latest `industrial_ci` code. Please see [this section in the updated readme](https://github.com/ros-industrial/industrial_ci/blob/master/README.rst#to-start-using-ci-config-stored-in-this-repo) (and detailed discussion https://github.com/ros-industrial/industrial_ci/issues/3 if interested).

**Comment by VictorLamoine** [comment]
My `travis.sh` script seems to be ok; I don't understand the error triggering:
https://travis-ci.org/InstitutMaupertuis/institut_maupertuis_robots_descriptions/builds/103383849#L166-L167

I already had that in my first test: (that why I tried the submodule way instead)
https://travis-ci.org/InstitutMaupertuis/institut_maupertuis_robots_descriptions/builds/103351376

**Comment by 130s** [comment]
Your `.travis.yml` is missing some initial setups, and seems like `sudo: required` solves your particular issue. See my fork https://github.com/130s/institut_maupertuis_robots_descriptions/pull/2.

(Unless you have specific requirement, copying a sample like [this one](https://github.com/ros-industrial/industrial_core/blob/indigo-devel/.travis.yml) may save you from extra complications.)

**Comment by VictorLamoine** [comment]
I think the rest is on me; `catkin_lint` is not happy about my packages :smile: 
``` 
institut_maupertuis_robots_descriptions/fanuc_r1000ia_grinding/fanuc_r1000ia_ensenso_n10_grinding_support$ catkin_lint 
WARNING: Package "ompl" does not follow the version conventions. It should not contain leading zeros (unless the number is 0).
fanuc_r1000ia_ensenso_n10_grinding_support: error: unknown run_depend 'grinding_eef_description'
fanuc_r1000ia_ensenso_n10_grinding_support: error: unknown run_depend 'fanuc_r1000ia_support'
fanuc_r1000ia_ensenso_n10_grinding_support: error: unknown run_depend 'ensenso_n10_description'
fanuc_r1000ia_ensenso_n10_grinding_support: error: unknown build_depend 'grinding_eef_description'
catkin_lint: checked 1 packages and found 4 problems
catkin_lint: 6 warnings have been ignored. Use -W1 to see them
```

Thanks for the fast support

**Pull request closed without merging**
