### PR TITLE
Update calibration for new grinding cell

### PR DESCRIPTION
**Pull request by KevinBollore**
@VictorLamoine Ready for review.
Do I need to cancel my modifications in test_calibration.cpp?

### CODE REVIEW

**Comment by VictorLamoine** [comment]
Let's not keep the modifications in `test_calibration.cpp`.
You forgot to include the SLS-2 XML `.cal` files in your PR.

**Comment by KevinBollore** [comment]
Where I'm supposed to put these `.cal` files?
I didn't find any location for them in the actual repository.

**Comment by VictorLamoine** [comment]
Put them in the resource directory,  they have never been uploaded yet

**Comment by KevinBollore** [comment]
@VictorLamoine All is done.

**Comment by VictorLamoine** [comment]
It's ok, we don't calibrate the sensor every day so we'll figure it out when looking at the files.

**Pull request merged**
